### ISSUE TITLE
Yo can someone help me 

### ISSUE THREAD

**Issue by kketg** [SomethingGeneric/ParkingContest#2]
Yo I don't know how to do anything halp pls?

**Comment by kketg** [comment]
How are we doing the database thing

**Comment by kketg** [comment]
Also NICK PoSt ThE dAnG fLoWcHaRt

**Comment by SomethingGeneric** [comment]
@kketg did you text him?

**Comment by kketg** [comment]
@SomethingGeneric Yeeeesss mattt
